package com.sample.microservice.awsdynamodb.domain;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@DynamoDBTable(tableName = "team")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Team  {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private List<String> members;

    @DynamoDBAttribute
    private String lead;

    @DynamoDBAttribute
    private String group;

    
}


